components:
  - changed-files:
    - any-glob-to-any-file:
        - 'components/**/*'
        - 'public/r/**/*'
        - 'scripts/sync-registry.js'

documentation:
  - changed-files:
    - any-glob-to-any-file:
        - 'README.md'
        - 'CONTRIBUTING.md'
        - 'CODE_OF_CONDUCT.md'
        - 'AI_POLICY.md'
        - 'SECURITY.md'

workflows:
  - changed-files:
    - any-glob-to-any-file:
        - '.github/workflows/**/*'
