blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/WatermelonCorp/watermellon-registry/discussions
    about: Ask questions, share ideas, and showcase what you've built.
